import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.49.8';
const $=id=>document.getElementById(id),status=$('status');
let db,user,isAdmin=false,urls=[];
const say=text=>{status.textContent=text;};
async function result(request){const {data,error}=await request;if(error)throw error;return data;}
async function busy(form,action){const button=form.querySelector('button');button.disabled=true;try{await action();}catch(error){say(error.message||'Please try again.');}finally{button.disabled=false;}}
function node(tag,text,cls){const el=document.createElement(tag);if(text)el.textContent=text;if(cls)el.className=cls;return el;}
async function cards(target,listings,review=false){target.replaceChildren();if(!listings.length){target.append(node('p',review?'No listings awaiting review.':'No listings yet. Add your first listing below.'));return;}
 for(const listing of listings){const card=node('article'),labels={draft:'Draft · Finish submitting',pending:'Pending approval',approved:'Approved · Live',rejected:'Not approved'};card.append(node('span',labels[listing.status],'badge'),node('h3',listing.title),node('p',listing.rental_type+' · '+listing.city+', GA'),node('p',new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(listing.rent)+'/month · Deposit: $'+listing.deposit),node('p',listing.description,'description'));
 const photos=node('div','','photos');card.append(photos);target.append(card);
 for(const photo of listing.listing_photos||[]){try{const signed=await result(db.storage.from('listing-photos').createSignedUrl(photo.path,600));const img=document.createElement('img');img.src=signed.signedUrl;img.alt=listing.title+' photo';img.loading='lazy';photos.append(img);}catch{photos.append(node('p','Photo could not load. Refresh to try again.'));}}
 if(listing.review_note)card.append(node('p','Admin note: '+listing.review_note));
 if(listing.status==='draft'&&!review){const submit=node('button','Submit saved listing');submit.addEventListener('click',async()=>{submit.disabled=true;try{await result(db.rpc('submit_customer_listing',{listing_id:listing.id}));await refresh();$('review').showModal();}catch(e){say(e.message);}finally{submit.disabled=false;}});card.append(submit);}
 if(review){for(const [decision,label] of [['approved','Approve and publish'],['rejected','Do not approve']]){const btn=node('button',label);btn.addEventListener('click',async()=>{btn.disabled=true;try{await result(db.rpc('review_customer_listing',{listing_id:listing.id,decision,note:''}));await refresh();say(decision==='approved'?'Listing approved and published.':'Listing was not approved. It remains in the customer’s account.');}catch(e){say(e.message);}finally{btn.disabled=false;}});card.append(btn);}}
 }
}
async function refresh(){if(!user)return;const own=await result(db.from('customer_listings').select('*,listing_photos(*)').eq('owner_id',user.id).order('created_at',{ascending:false}));await cards($('mine'),own);if(isAdmin){const queue=await result(db.from('customer_listings').select('*,listing_photos(*)').eq('status','pending').order('submitted_at'));await cards($('queue'),queue,true);}}
async function sessionChanged(session){user=session?.user;$('auth').hidden=!!user;$('account').hidden=!user;$('signout').hidden=!user;isAdmin=false;if(!user){$('mine').replaceChildren();$('queue').replaceChildren();say('Sign in to view or add your listings.');return;}isAdmin=await result(db.rpc('is_listing_admin'));$('admin').hidden=!isAdmin;await refresh();say('Signed in as '+user.email);}
$('photo-files').addEventListener('change',()=>{urls.forEach(URL.revokeObjectURL);urls=[];$('photo-preview').replaceChildren();for(const file of [...$('photo-files').files].slice(0,10)){if(!['image/jpeg','image/png','image/webp'].includes(file.type))continue;const img=document.createElement('img');img.src=URL.createObjectURL(file);urls.push(img.src);img.alt='Selected listing photo';$('photo-preview').append(img);}});
$('view').addEventListener('click',()=>{$('review').close();$('mine').scrollIntoView({behavior:'smooth',block:'start'});});
$('refresh').addEventListener('click',()=>refresh().catch(e=>say(e.message)));
$('signout').addEventListener('click',async()=>{try{await result(db.auth.signOut());await sessionChanged(null);}catch(e){say(e.message);}});
$('signin').addEventListener('submit',event=>{event.preventDefault();busy(event.currentTarget,async()=>{const data=new FormData(event.currentTarget),login=await result(db.auth.signInWithPassword({email:data.get('email'),password:data.get('password')}));event.target.reset();await sessionChanged(login.session);});});
$('signup').addEventListener('submit',event=>{event.preventDefault();busy(event.currentTarget,async()=>{const data=new FormData(event.currentTarget),signup=await result(db.auth.signUp({email:data.get('email'),password:data.get('password'),options:{emailRedirectTo:location.origin+'/listing-account.html'}}));event.target.reset();if(signup.session)await sessionChanged(signup.session);else say('Check your email to confirm your account, then sign in.');});});
$('new-listing').addEventListener('submit',event=>{event.preventDefault();busy(event.currentTarget,async()=>{
 if(!user)throw Error('Sign in before adding a listing.');const files=[...$('photo-files').files];if(files.length<1||files.length>10)throw Error('Choose 1–10 photos.');if(files.some(f=>f.size>10485760||!['image/jpeg','image/png','image/webp'].includes(f.type)))throw Error('Use JPG, PNG, or WebP photos up to 10 MB each.');
 const input=Object.fromEntries(new FormData(event.currentTarget));input.rent=Number(input.rent);input.deposit=Number(input.deposit);say('Saving your listing and uploading photos…');
 const listing=await result(db.from('customer_listings').insert(input).select().single());
 try{for(const [position,file] of files.entries()){const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[file.type],path=user.id+'/'+listing.id+'/'+crypto.randomUUID()+'.'+ext;await result(db.storage.from('listing-photos').upload(path,file,{contentType:file.type,upsert:false}));await result(db.from('listing_photos').insert({listing_id:listing.id,path,position}));}await result(db.rpc('submit_customer_listing',{listing_id:listing.id}));}
 catch(e){await refresh();throw Error('Your listing is saved as a draft. '+e.message+' Please contact APLYNX if photos need to be added.');}
 event.target.reset();urls.forEach(URL.revokeObjectURL);urls=[];$('photo-preview').replaceChildren();$('add').open=false;await refresh();say('Your listing is saved in your account and awaiting admin approval.');$('review').showModal();
 });});
try{const config=await fetch('/api/listing-config').then(r=>r.json());if(config.error)throw Error(config.error);db=createClient(config.url,config.key);const current=await result(db.auth.getSession());await sessionChanged(current.session);db.auth.onAuthStateChange((event,session)=>{if(['SIGNED_OUT','TOKEN_REFRESHED','PASSWORD_RECOVERY'].includes(event))setTimeout(()=>sessionChanged(session).catch(e=>say(e.message)),0);});}catch(error){say(error.message);}
